class Autogenerated {
  List<Data>? data;
  bool? success;
  String? message;
  int? lastPage;

  Autogenerated({this.data, this.success, this.message, this.lastPage});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      data = <Data>[];
      json['data'].forEach((v) {
        data!.add(Data.fromJson(v));
      });
    }
    success = json['success'];
    message = json['message'];
    lastPage = json['lastPage'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    data['success'] = success;
    data['message'] = message;
    data['lastPage'] = lastPage;
    return data;
  }
}

class Data {
  int? id;
  String? name;
  String? imageSource;
  String? fileSource;
  int? albumId;
  Album? album;

  Data(
      {this.id,
        this.name,
        this.imageSource,
        this.fileSource,
        this.albumId,
        this.album});

  Data.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    imageSource = json['imageSource'];
    fileSource = json['fileSource'];
    albumId = json['albumId'];
    album = json['album'] != null ? Album.fromJson(json['album']) : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['imageSource'] = imageSource;
    data['fileSource'] = fileSource;
    data['albumId'] = albumId;
    if (album != null) {
      data['album'] = album!.toJson();
    }
    return data;
  }
}

class Album {
  int? id;
  String? name;
  String? imageSource;
  int? singerId;
  Singer? singer;
  List<String>? musics;

  Album(
      {this.id,
        this.name,
        this.imageSource,
        this.singerId,
        this.singer,
        this.musics});

  Album.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    imageSource = json['imageSource'];
    singerId = json['singerId'];
    singer =
    json['singer'] != null ? Singer.fromJson(json['singer']) : null;
    musics = json['musics'].cast<String>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['imageSource'] = imageSource;
    data['singerId'] = singerId;
    if (singer != null) {
      data['singer'] = singer!.toJson();
    }
    data['musics'] = musics;
    return data;
  }
}

class Singer {
  int? id;
  String? name;
  String? imageSource;
  bool? isBest;

  Singer({this.id, this.name, this.imageSource, this.isBest});

  Singer.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    imageSource = json['imageSource'];
    isBest = json['isBest'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['imageSource'] = imageSource;
    data['isBest'] = isBest;
    return data;
  }
}